### PR TITLE
test: IgnoreUpdates for job module

### PR DESCRIPTION
**Pull request by akocbek**
### Description

On second `tf plan` terraform provider adds changes 
```
~ resource "ibm_code_engine_job" "ce_job" {
        id                            = "5e7a7942-774b-4413-a83a-2aa8432976bb/ce-jobs-test-job-2"
        name                          = "ce-jobs-test-job-2"
        # (19 unchanged attributes hidden)

      - run_env_variables {
          - name  = "CE_REGION" -> null
          - type  = "literal" -> null
          - value = "us-south" -> null
        }
      - run_env_variables {
          - name  = "CE_PROJECT_ID" -> null
          - type  = "literal" -> null
          - value = "5e7a7942-774b-4413-a83a-2aa8432976bb" -> null
        }
      - run_env_variables {
          - name  = "CE_API_BASE_URL" -> null
          - type  = "literal" -> null
          - value = "https://api.us-south.codeengine.cloud.ibm.com/" -> null
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by akocbek** [comment]
provider issue: https://github.com/IBM-Cloud/terraform-provider-ibm/issues/4719

**Review by shemau — DISMISSED** [review]
LGTM

I would have been inclined to put a comment next to the IgnoreUpdates code so that at some point when the issue is fixed they can be removed.

**Pull request merged**
